apiVersion: serialmanipulatordriver.timr.io/v1alpha1
metadata:
  name: robotDriver2
  description: Robot driver configuration
kind: SerialManipulatorDriver
spec:
  jointDescriptionPaths:
    - /home/kai/Projects/timr/ros2_ws/src/driver/config/robot2/joint1.yaml
    - /home/kai/Projects/timr/ros2_ws/src/driver/config/robot2/joint2.yaml
    - /home/kai/Projects/timr/ros2_ws/src/driver/config/robot2/joint3.yaml
    - /home/kai/Projects/timr/ros2_ws/src/driver/config/robot2/joint4.yaml
    - /home/kai/Projects/timr/ros2_ws/src/driver/config/robot2/joint5.yaml
    - /home/kai/Projects/timr/ros2_ws/src/driver/config/robot2/joint6.yaml
  canInterface: 
    name: can1